### ISSUE TITLE
Threebot improvements & features unplanned

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1784]
## Features

- [ ] Interactive playground actors threefoldtech/jumpscaleX_threebot#288
- [ ] Registry package threefoldtech/jumpscaleX_threebot#229
- [ ] Improve wiki loading time threefoldtech/jumpscaleX_threebot#209
- [ ] calendar package threefoldtech/jumpscaleX_threebot#37
