### ISSUE TITLE
Clear seperation between testnet and mainnet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1798]
### Description
Testnet is testnet and mainnet is mainnet, also they should have as much of the functionality equal

This is a story to list some of the issues:
- [x] Drop the 3bot import from another network functionality #1793
- [x] A testnet 3bot should not have a mainnet identity and vice versa #1799
- [x] Drop the "Create testnet funded wallet" from the dashboard #1800 -this one under discussion not accepted-
