### ISSUE TITLE
3bot UX improvements

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1821]
A story to gather some ux improvements for the 3bot

- [x] Change "Update Trustlines" in the 3bot wallet details #1822
- [x] New wallet should not be available on the main 3bot dashboard page #1823
- [x] Farm mgmt in main 3bot menu while irrelevant for non farmers #1824
- [x] Extending a capacity pool in a 3bot is too complex #1825: moved to next 
- [x] typo in 3bot deployer #1826

**Comment by xmonader** [comment]
Will reviist the extending pools in the next milestone
