### ISSUE TITLE
circles_tools v2 [development_circles]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#1845]
# tool to manage our circles

- to not introduce yet another tool we want to keep on doing our funnels, projectmgmt & circle mgmt from 1 tool
- one of the downsides of taiga is the reporting is not very good, this we want to resolve with this circles tool

## features

- wiki which will show all stories, funnels, opportunities, deals, tasks, ...
    - wiki is published using our publishing tools so its searchable
    - will make it very easy for everyone to see status of tasks, funnel, ... more reports will be created as we go
    - wiki to show which tasks, deals, stories, ... are beyond deadline
- tool to move stories/deals/opportunities between circles
- tool to create circles
- tool to export/import

## todo:

- [x] reporting specs see: https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/reportingtool.md
- [x] define the models: https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/models.md
- [x] circle creation specs see: https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/circle_creation.md
- [x] export specs see: https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/export_import.md
- [x] import specs see: https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/export_import.md
- [x] move funnel, story between circles: https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/story_move.md

## phase 2

- telegram bot will be created to make it easy for everyone to use this tool and get warned for items which are needed

**Comment by xmonader** [comment]
All should be done https://github.com/threefoldtech/js-sdk/pull/1643

**Comment by hossnys** [comment]
All functionalities tested as documented [here](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/tutorials/taiga_client.md)
using this instance of staging circles https://staging-circles.threefold.me/
