### ISSUE TITLE
eVDC deployer: Testing issues found

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2187]
## Combination card for a number of (minor) issues:
- [ ] Item 1: text optimisation :https://github.com/threefoldtech/js-sdk/issues/2192
- [ ] Item 2: button optimisation https://github.com/threefoldtech/js-sdk/issues/2193
- [ ] Item 3: information presented optimisation https://github.com/threefoldtech/js-sdk/issues/2194
- [ ] Item 4: deployment takes long / waiting screen not progressing properly https://github.com/threefoldtech/js-sdk/issues/2195

**Comment by weynandkuijpers** [comment]
Also this screen contains a ```Next``` and ```Back``` button which cannot be pressed
- successful payment it auto advances to "VDC deployment" screen
- if time out occurs - error message with a restart button to restart the eVDC provisioning process

Why keep the next / back button?

**Comment by weynandkuijpers** [comment]
Item 3

In the provisioning process we show a screen that sais "Testrun for deployment".  I understand we do it but do we have to advocate this to the outside world.  Maybe we can find a better test "Searching for optimal deployment target(s)"

**Comment by weynandkuijpers** [comment]
## Item 4

Overall deployment time takes long for a VDC (did not time but long).  Last screen was "Funding difference" and this stayed on for very long. I pressed "reload page" in the browser and then was returned to the vdc deployer landing page after login: https://vdc.testnet.grid.tf/vdc/#/

Pushing "List VDC's" show me that the VDC was deployed and operational.  So the "Funding difference" screen was no progressing.

**Comment by weynandkuijpers** [comment]
The issue split into multiple issues and directly related from the original card.  Issie obsolete.
