### ISSUE TITLE
3bot admin: kubernetes updates (more sizes, public ip, extension)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2225]
- [x] kubernetes sizes support https://github.com/threefoldtech/js-sdk/issues/1836
- [x] kubernetes allow extending: https://github.com/threefoldtech/js-sdk/issues/2224
- [x] kubernetes public ip support https://github.com/threefoldtech/js-sdk/issues/2223 
- [x]  Kubernetes delete button https://github.com/threefoldtech/js-sdk/issues/2350
- [x]  Kubenetes list nodes for deployed solutions https://github.com/threefoldtech/js-sdk/issues/2351

**Comment by RafyAmgadBenjamin** [comment]
Done 
### Branch 
`development_vdc_kube`
### PR
https://github.com/threefoldtech/js-sdk/pull/2447

**Comment by MElborolossy** [comment]
Verifying
