### ISSUE TITLE
VDC: marketplace solutions to support threefold connect 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2445]
- [x] zeroci
- [ ] peertube
- [ ] mattermost
- [ ] discourse
- [ ] gitea 
- [ ] cryptpad
- [ ] taiga
- [ ] monitoring stack? (don't think that should be included)

## phase 1
for each of the solutions
- [ ] prepare a fork
- [ ] prepare the build pipeline (build pipelines don't work on forks on github)
- [ ] prepare the helm charts
- [ ] make sure VDC marketplace works against the forked solutions
- [ ] integrate threefold connect (should be a button to loging with threefold connect that starts the auth flow) + callback endpoint that creates the users -how do we deal with different roles?- if these solutions are exposed on the public internet?
- [ ] use the current [oauth proxy](oauth.threefold.io) 

## phase 2
- run [oauth proxy](https://github.com/threefoldtech/oauth-proxy) per each VDC and allow that to be used for all of the solutions
