### ISSUE TITLE
VDC: marketplace solutions to support threefold connect 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2584]
- [x] zeroci  @samaradel 
- [x] peertube https://github.com/threefoldtech/tf-peertube/issues/1 @OmarElawady @m-motawea @waleedhammam 
- [x] mattermost https://github.com/threefoldtech/tf-mattermost/issues/1 @ashraffouda @RafyAmgadBenjamin 
- [x] gitea  https://github.com/threefoldtech/tf-gitea/issues/12 @dmahmouali @ranatrk 
- [x] cryptpad  https://github.com/threefoldtech/tf-cryptpad/issues/1 @AhmedSa-mir @abom 

## phase 1
for each of the solutions
- prepare a fork
- prepare the build pipeline (build pipelines don't work on forks on github)
- prepare the helm charts
- make sure VDC marketplace works against the forked solutions
- integrate threefold connect (should be a button to loging with threefold connect that starts the auth flow) + callback endpoint that creates the users -how do we deal with different roles?- if these solutions are exposed on the public internet?
- use the current [oauth proxy](https://oauth.threefold.io) 

note: this issue doesn't address anything related to mobile/desktop apps for the solutions, it'd be only usable from the web browser

**Comment by RafyAmgadBenjamin** [comment]
verifying this issue

**Comment by RafyAmgadBenjamin** [comment]
Verification
- [ ] zeroci 
- [ ] peertube crystaluniverse/tf-peertube#1 
- [ ] mattermost crystaluniverse/tf-mattermost#1 
- [ ] gitea crystaluniverse/tf-gitea#12 
- [ ] cryptpad crystaluniverse/tf-cryptpad#1
