### ISSUE TITLE
admin panel bugs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#38]
- [x] protect /admin url #31 
- [x] creating alerts problem #34 
- [x] improve wallet creation #36  
- [x] add package by git url #35 
- [x] metadata problem in chatflows #33
