### ISSUE TITLE
Overall review of the dashboard for grid 2.2 release [development_capacity_ui_improve]

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#384]
In this issue I'll consolidated all the open issues regarding the dashboard:

- [x] [Farm Management: Users should be able to move farms to another 3bot](https://github.com/threefoldtech/js-sdk/issues/373)
- [x] [ show clock with utc time for the users on the dashboard and the marketplace](https://github.com/threefoldtech/js-sdk/issues/365)
- [x] [Improve the info messages shown in chatflows](https://github.com/threefoldtech/js-sdk/issues/356)
- [x] [Improve the error messages shown in chatflows](https://github.com/threefoldtech/js-sdk/issues/416)
- [x] [Add a summary of the capacity pool on the dashboard home page](https://github.com/threefoldtech/js-sdk/issues/380)
- [x] [allow to see the full log line](https://github.com/threefoldtech/js-sdk/issues/381)
- [x] [Capacity pool UI](https://github.com/threefoldtech/js-sdk/issues/382)
- [x] [Show somewhere on the dashboard which network the user is currently connected to](https://github.com/threefoldtech/js-sdk/issues/383)
- [x] [Extending a pool should not be hidden behind a new button](https://github.com/threefoldtech/js-sdk/issues/385)
- [x] [Extending a pool with empty (default) values causes an unclear error](https://github.com/threefoldtech/js-sdk/issues/410)
- [x] [Improve minio setup wizard](https://github.com/threefoldtech/js-sdk/issues/411)
- [x] [workload detail vue should show a proper UI for workload.info field](https://github.com/threefoldtech/js-sdk/issues/476)

**Comment by hossnys** [comment]
all listed issues is done and verified .
