### ISSUE TITLE
tf grid marketplace homepage feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#686]
- [x] [Threefold Marketplace should be TF Grid Marketplace](https://github.com/threefoldtech/js-sdk/issues/680)

<img width="300" alt="Screenshot 2020-08-27 at 10 11 05" src="https://user-images.githubusercontent.com/43240801/91416459-b4b45900-e84f-11ea-97f4-c58343d9916d.png">

- [x] [ 'S' should be big on 'Solutions', all titles should have first letter on Caps](https://github.com/threefoldtech/js-sdk/issues/688).
<img width="265" alt="Screenshot 2020-08-27 at 10 22 01" src="https://user-images.githubusercontent.com/43240801/91425434-6b6a0680-e85b-11ea-9fe5-dca195dff951.png">

- [x] ['Capacity Pools' 'Network' should be on the first top 2 on infrastructure.](https://github.com/threefoldtech/js-sdk/issues/688)
<img width="500" alt="Screenshot 2020-08-27 at 11 50 49" src="https://user-images.githubusercontent.com/43240801/91425575-9eac9580-e85b-11ea-81d5-df54c066abfc.png">

- [x] can we agree to never write 3Bot as threebot anymore....
<img width="500" alt="Screenshot 2020-08-27 at 12 40 22" src="https://user-images.githubusercontent.com/43240801/91433693-f7802c00-e863-11ea-96b5-5dda393ed844.png">

**Comment by xmonader** [comment]
- 3Bot should stay 3Bot. the mobile application is called `3bot connect` not `3bot server connect nor 3bot admin connect`. Application used to login/connect to a 3Bot 
- 3Bot should be in Apps not because it's simplified, the user doesn't bother with pools, networks, .. etc. @despiegk already signed off on making it an App
- Marketplace is enduser first, so probably 3Bot should be the first available app, and Apps to be the first section to be shown
- For infrastructure solutions, should be ordered indeed with `Pool`, `Network`, `Ubuntu` 
- Difference between New and Workloads is new starts the chatflow for new X, while workloads you see all of the deployed X instances and a way to create a new X, this isn't an object to change at this point.

**Comment by xmonader** [comment]
other issues tracked in #709  #710
